[package]
name = "panoptes-config-program"
version = "1.7.3"
description = "Panoptes Config program"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-config-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
panoptes-sdk = { path = "../../sdk", version = "=1.7.3" }

[dev-dependencies]
panoptes-logger = { path = "../../logger", version = "=1.7.3" }

[lib]
crate-type = ["lib"]
name = "panoptes_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
