[package]
name = "panoptes-cargo-build-bpf"
version = "1.7.3"
description = "Compile a local package and all of its dependencies using the Panoptes BPF SDK"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
homepage = "https://panoptes.com/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.3"
regex = "1.4.5"
cargo_metadata = "0.12.0"
panoptes-sdk = { path = "..", version = "=1.7.3" }
panoptes-download-utils = { path = "../../download-utils", version = "=1.7.3" }
tar = "0.4.28"

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
