[package]
name = "panoptes-bpf-loader-program"
version = "1.7.3"
description = "Panoptes BPF loader"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-bpf-loader-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
rand_core = "0.6.2"
sha3 = "0.9.1"
panoptes-measure = { path = "../../measure", version = "=1.7.3" }
panoptes-runtime = { path = "../../runtime", version = "=1.7.3" }
panoptes-sdk = { path = "../../sdk", version = "=1.7.3" }
panoptes_rbpf = "=0.2.11"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
rustversion = "1.0.4"

[lib]
crate-type = ["lib"]
name = "panoptes_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
