[package]
name = "panoptes-version"
version = "1.7.3"
description = "Panoptes Version"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-version"
edition = "2018"

[dependencies]
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
panoptes-frozen-abi = { path = "../frozen-abi", version = "=1.7.3" }
panoptes-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.7.3" }
panoptes-logger = { path = "../logger", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }

[lib]
name = "panoptes_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
