[package]
name = "panoptes-rpc"
version = "1.7.3"
description = "Panoptes RPC"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-rpc"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
bs58 = "0.3.1"
crossbeam-channel = "0.4"
itertools = "0.9.0"
jsonrpc-core = "17.1.0"
jsonrpc-core-client = { version = "17.1.0", features = ["ipc", "ws"] }
jsonrpc-derive = "17.1.0"
jsonrpc-http-server = "17.1.0"
jsonrpc-pubsub = "17.1.0"
jsonrpc-ws-server = "17.1.0"
libc = "0.2.81"
log = "0.4.11"
regex = "1.3.9"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
panoptes-account-decoder = { path = "../account-decoder", version = "=1.7.3" }
panoptes-client = { path = "../client", version = "=1.7.3" }
panoptes-faucet = { path = "../faucet", version = "=1.7.3" }
panoptes-gossip = { path = "../gossip", version = "=1.7.3" }
panoptes-ledger = { path = "../ledger", version = "=1.7.3" }
panoptes-measure = { path = "../measure", version = "=1.7.3" }
panoptes-metrics = { path = "../metrics", version = "=1.7.3" }
panoptes-perf = { path = "../perf", version = "=1.7.3" }
panoptes-poh = { path = "../poh", version = "=1.7.3" }
panoptes-runtime = { path = "../runtime", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }
panoptes-storage-bigtable = { path = "../storage-bigtable", version = "=1.7.3" }
panoptes-transaction-status = { path = "../transaction-status", version = "=1.7.3" }
panoptes-version = { path = "../version", version = "=1.7.3" }
panoptes-vote-program = { path = "../programs/vote", version = "=1.7.3" }
spl-token-v2-0 = { package = "spl-token", version = "=3.1.1", features = ["no-entrypoint"] }
tokio = { version = "1", features = ["full"] }
tokio_02 = { version = "0.2", package = "tokio", features = ["full"] }
tokio-util = { version = "0.3", features = ["codec"] } # This crate needs to stay in sync with tokio_02, until that dependency can be removed

[dev-dependencies]
serial_test = "0.4.0"
panoptes-logger = { path = "../logger", version = "=1.7.3" }
panoptes-net-utils = { path = "../net-utils", version = "=1.7.3" }
panoptes-stake-program = { path = "../programs/stake", version = "=1.7.3" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "panoptes_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
