[package]
name = "panoptes-noop-program"
version = "1.7.3"
description = "Panoptes Noop program"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-noop-program"
edition = "2018"

[dependencies]
log = "0.4.11"
panoptes-logger = { path = "../../logger", version = "=1.7.3" }
panoptes-sdk = { path = "../../sdk", version = "=1.7.3" }

[lib]
crate-type = ["lib", "cdylib"]
name = "panoptes_noop_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
