[package]
name = "panoptes-exchange-program"
version = "1.7.3"
description = "Panoptes Exchange program"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-exchange-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
log = "0.4.11"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = "1.0.122"
serde_derive = "1.0.103"
panoptes-logger = { path = "../../logger", version = "=1.7.3" }
panoptes-metrics = { path = "../../metrics", version = "=1.7.3" }
panoptes-sdk = { path = "../../sdk", version = "=1.7.3" }
thiserror = "1.0"

[dev-dependencies]
panoptes-runtime = { path = "../../runtime", version = "=1.7.3" }

[lib]
crate-type = ["lib", "cdylib"]
name = "panoptes_exchange_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
