[package]
name = "panoptes-notifier"
version = "1.7.3"
description = "Panoptes Notifier"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-notifier"
edition = "2018"

[dependencies]
log = "0.4.11"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "panoptes_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
