[package]
name = "panoptes-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
edition = "2018"
version = "1.7.3"
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-stake-accounts"

[dependencies]
clap = "2.33.1"
panoptes-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
panoptes-cli-config = { path = "../cli-config", version = "=1.7.3" }
panoptes-client = { path = "../client", version = "=1.7.3" }
panoptes-remote-wallet = { path = "../remote-wallet", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }
panoptes-stake-program = { path = "../programs/stake", version = "=1.7.3" }

[dev-dependencies]
panoptes-runtime = { path = "../runtime", version = "=1.7.3" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
