[package]
name = "panoptes-secp256k1-program"
description = "Panoptes Secp256k1 program"
version = "1.7.3"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-secp256k1-program"
repository = "https://github.com/panoptes-labs/panoptes"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
panoptes-sdk = { path = "../../sdk", version = "=1.7.3" }
libsecp256k1 = "0.3.5"
sha3 = "0.9.1"
digest = "0.9.0"
bincode = "1.3.1"
rand = "0.7.0"
panoptes-logger = { path = "../../logger", version = "=1.7.3" }

[lib]
crate-type = ["lib"]
name = "panoptes_secp256k1_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
