[package]
name = "panoptes-storage-proto"
version = "1.7.3"
description = "Panoptes Storage Protobuf Definitions"
authors = ["Panoptes Maintainers <maintainers@panoptes.com>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-storage-proto"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
prost = "0.7.0"
serde = "1.0.122"
serde_derive = "1.0.103"
panoptes-account-decoder = { path = "../account-decoder", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }
panoptes-transaction-status = { path = "../transaction-status", version = "=1.7.3" }

[lib]
crate-type = ["lib"]
name = "panoptes_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
