[package]
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
edition = "2018"
name = "panoptes-stake-monitor"
description = "Blockchain, Rebuilt for Scale"
version = "1.7.3"
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-stake-monitor"

[dependencies]
clap = "2.33.1"
console = "0.14.1"
log = "0.4.11"
serde = "1.0.122"
serde_yaml = "0.8.13"
panoptes-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
panoptes-cli-config = { path = "../cli-config", version = "=1.7.3" }
panoptes-client = { path = "../client", version = "=1.7.3" }
panoptes-logger = { path = "../logger", version = "=1.7.3" }
panoptes-metrics = { path = "../metrics", version = "=1.7.3" }
panoptes-rpc = { path = "../rpc", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }
panoptes-transaction-status = { path = "../transaction-status", version = "=1.7.3" }
panoptes-version = { path = "../version", version = "=1.7.3" }

[dev-dependencies]
serial_test = "0.4.0"
panoptes-local-cluster = { path = "../local-cluster", version = "=1.7.3" }
panoptes-core = { path = "../core", version = "=1.7.3" }
tempfile = "3.1.0"

[[bin]]
name = "panoptes-stake-monitor"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
