[package]
name = "panoptes-rayon-threadlimit"
version = "1.7.3"
description = "panoptes-rayon-threadlimit"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/panoptes-labs/panoptes"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
