[package]
name = "panoptes-cargo-test-bpf"
version = "1.7.3"
description = "Execute all unit and integration tests after building with the Panoptes BPF SDK"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
homepage = "https://panoptes.com/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.12.0"

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
