[package]
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
edition = "2018"
name = "panoptes-install"
description = "The panoptes cluster software installer"
version = "1.7.3"
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
documentation = "https://docs.rs/panoptes-install"

[dependencies]
atty = "0.2.11"
bincode = "1.3.1"
bzip2 = "0.3.3"
chrono = { version = "0.4.11", features = ["serde"] }
clap = { version = "2.33.1" }
console = "0.14.1"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs-next = "2.0.0"
indicatif = "0.15.0"
lazy_static = "1.4.0"
nix = "0.19.0"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.13"
panoptes-clap-utils = { path = "../clap-utils", version = "=1.7.3" }
panoptes-client = { path = "../client", version = "=1.7.3" }
panoptes-config-program = { path = "../programs/config", version = "=1.7.3" }
panoptes-logger = { path = "../logger", version = "=1.7.3" }
panoptes-sdk = { path = "../sdk", version = "=1.7.3" }
panoptes-version = { path = "../version", version = "=1.7.3" }
semver = "0.9.0"
tar = "0.4.28"
tempfile = "3.1.0"
url = "2.1.1"

[target."cfg(windows)".dependencies]
winapi = "0.3.8"
winreg = "0.7"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
