[package]
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
edition = "2018"
name = "panoptes-scripts"
description = "Blockchain, Rebuilt for Scale"
version = "1.7.3"
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
homepage = "https://panoptes.com/"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0.122", features = ["derive"] }

[[bin]]
name = "panoptes-csv-to-validator-infos"
path = "src/csv_to_validator_infos.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
