[package]
name = "panoptes-upload-perf"
version = "1.7.3"
description = "Metrics Upload Utility"
authors = ["Panoptes Maintainers <maintainers@panoptes.foundation>"]
repository = "https://github.com/panoptes-labs/panoptes"
license = "Apache-2.0"
edition = "2018"
homepage = "https://panoptes.com/"
publish = false

[dependencies]
serde_json = "1.0.56"
panoptes-metrics = { path = "../metrics", version = "=1.7.3" }

[[bin]]
name = "panoptes-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
